config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get "/users", to: "details#index"
  root "posts#index"
  resources :users do
    get "/profile_page", to: "users#profile_page", as: 'profile_page'
    resources :posts do
      resources :comments
    end
    resources :friendrequests
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/friendrequest.rb
class Friendrequest < ApplicationRecord
    belongs_to :sender, class_name: "User", foreign_key: "sender_id"
    belongs_to :receiver, class_name: "User", foreign_key: "receiver_id"

end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :friend_requests_sent, class_name: "Friendrequest", foreign_key: "sender_id", dependent: :destroy
  has_many :friend_requests_receivers, through: :friend_requests_sent, source: :receiver, dependent: :destroy

  has_many :friend_requests_received, class_name: "Friendrequest", foreign_key: "receiver_id", dependent: :destroy
  has_many :friend_requests_senders, through: :friend_requests_received, source: :sender, dependent: :destroy

  has_many :comments, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_one_attached :image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected
  
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:image, :name])
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    def destroy
        @comment=current_user.comments.find(params[:id])
        @comment.destroy
        
    end

    def edit
        @post=Post.find(params[:post_id])
        @comment=Comment.find(params[:id])
        @user=User.find(params[:user_id])
    end

    def update
        @comment=Comment.find(params[:id])
        @comment.update(comment_params)
    end
    

    def create
        @post=Post.find(params[:post_id])
        @comment=Post.find(params[:post_id]).comments.create(comment_params.merge(user_id: current_user.id))
    end

    private
        def comment_params
            params.require(:comment).permit(:body)
        end
end

app/controllers/details_controller.rb
class DetailsController < ApplicationController
  def index
    @allusers=User.all
    @allrequests= User.find(current_user.id).friend_requests_received.where(status:"pending")
    @allfriends= User.find(current_user.id).friend_requests_received.where(status:"approved").pluck(:sender_id)+User.find(current_user.id).friend_requests_sent.where(status:"approved").pluck(:receiver_id)
    @all_posts= Post.all
  end
end

app/controllers/friendrequests_controller.rb
class FriendrequestsController < ApplicationController
    def create
        @friend=Friendrequest.create(status:"pending", sender_id:params[:user_id], receiver_id:params[:receiver_id])
        @friend_id=@friend.id 
    end

    
    def update
        @friend=Friendrequest.find(params[:friendrequest_id])
        @friend.update(status:"approved")
    end
    def destroy
        @friend=Friendrequest.find(params[:id])
        @friend.destroy
    end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    def new
        @post=Post.new
    end

    def index
        @allusers=User.all
        @allrequests= User.find(current_user.id).friend_requests_received.where(status:"pending")
        @allfriends_friendrequest_received = User.find(current_user.id).friend_requests_received.where(status:"approved")
        @allfriends_friendrequest_sent = User.find(current_user.id).friend_requests_sent.where(status:"approved")
        @all_posts= Post.all
         
        
    end
    def create
        @post= current_user.posts.create(post_params)
    end
    
    def show
        @post=Post.find(params[:id])
        @comment=Comment.new
        @all_comments=Post.find(@post.id).comments
    end

    def destroy
        @post=Post.find(params[:id])
        @post.destroy
    end

    def edit
        @post=Post.find(params[:id])
    end

    def update
        
        @post=Post.find(params[:id])
        @post.update(post_params)
        @post_body= @post.body
        

        #redirect_to user_post_path(current_user.id, @post.id)
        respond_to do |format|
            format.html { redirect_to root_path }
            format.js 
        end
    end

    private
        def post_params
            params.require(:post).permit(:title, :body)
        end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def profile_page
        @user_details= User.find(params[:user_id])
    end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/details_helper.rb
module DetailsHelper
end

app/helpers/friend_requests_helper.rb
module FriendRequestsHelper
end

app/helpers/friendrequests_helper.rb
module FriendrequestsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/create.js.erb
$('#comments_id').append("<%= j render 'partial/deleting_user_comment' ,  user_comment: @comment   %>");
$('#comment_body').val('');

app/views/comments/destroy.js.erb
$('.user-<%= @comment.id %>').remove();

app/views/comments/edit.html.erb
<%= form_with model:[@user, @post, @comment] do |f| %>
    <div>
        <br>
        <%= f.label :body %> <br> 
        <%= f.text_field :body %> <br>
    </div>

    <div> <br>
        <%= f.submit %>
    </div>
<% end %>

app/views/comments/edit.js.erb
$( ".newusermodal").html("<%= escape_javascript render('partial/edit_comment', post:@post, comment:@comment)  %>");

app/views/comments/update.js.erb
$('.post-content .post-<%= @comment.post_id %>').text('<%= @comment.body %>');

$('#newcommentmodal').modal('toggle');

app/views/details/index.html.erb
<h1> All Posts </h1>
You are currently logged in as <%= current_user.email %>
<% for post in @all_posts %>
    <p>
        <%= link_to post.title , user_post_path(current_user.id, post.id) %> <br>
        By <%= User.find(post.user_id).email %> 
    </p>
<% end %>

<h2> ALl request </h2>
<% for allrequests in @allrequests %>
    <p>
        <%= User.find(allrequests.sender_id).email %> <%= link_to "Accept", user_friendrequest_path(current_user, allrequests.id, friendrequest_id: allrequests.id ), method: :patch %> <%= link_to "Reject", user_friendrequest_path(current_user, allrequests.id, friendrequest_id: allrequests.id ), method: :delete %>
    </p>
<% end %>

<h3> All Friends </h3>
<% for allfriends in @allfriends %>
    <p>
        <%= User.find(allfriends).email %> <%= link_to "Remove Friend", user_friendrequest_remove_user_path( current_user, allfriends, friendrequest_id: allfriends ), method: :delete %>
    </p>    
<% end %> 
<h4> All USers </h4>
<% for allusers in @allusers %>
    <% if allusers.id== current_user.id %>
        <% next %>
    <% else %>
        <p>
            <%= allusers.id %>
            <%= allusers.email %> <%= link_to "send friend request", user_friendrequests_path( current_user.id, allusers.id, receiver: allusers.id ), method: :post %>
        </p>
    <% end %>

<% end %>

<br>
<br>
<%= link_to "New Post", new_user_post_path(current_user) %>
<br><br>
<%= link_to "Sign Out", destroy_user_session_path, method: :delete %>

app/views/friendrequests/create.js.erb
var $userClass2 = $('.user-class-<%= @friend.receiver_id %>');

    var $sendFriendRequest = $userClass2.find('a');

   
    $userClass2.html('Friend Request send! <%= link_to "Undo", user_friendrequest_path(current_user, @friend ), method: :delete, remote:true ,class:"btn btn-info" %>');

    $sendFriendRequest.hide();

app/views/friendrequests/destroy.js.erb
debugger
$( ".friendrequest-<%= @friend.id %>").remove();
$( ".friendship-<%= @friend.id %>").remove();
var $userClass2 = $('.user-class-<%= @friend.receiver_id %>');

    var $sendFriendRequest = $userClass2.find('a');

   
    $userClass2.html('<%= link_to User.find(@friend.receiver_id).name, user_profile_page_path(@friend.receiver_id), class:"link-to-title" %> <%= link_to "send friend request", user_friendrequests_path( current_user.id, receiver_id: @friend.receiver_id), method: :post, remote:true, class:"btn btn-primary" %>');

var $userClass2 = $('.user-class-<%= @friend.sender_id %>');

    var $sendFriendRequest = $userClass2.find('a');

   
    $userClass2.html('<%= link_to User.find(@friend.receiver_id).name, user_profile_page_path(@friend.receiver_id), class:"link-to-title" %> <%= link_to "send friend request", user_friendrequests_path( current_user.id, receiver_id: @friend.receiver_id), method: :post, remote:true, class:"btn btn-primary" %>');

app/views/friendrequests/update.js.erb
$( ".friendrequest-<%= @friend.id %>").remove();
$( "#allfriendslist").append("<%= j render 'partial/all_friends_list' ,  allfriends:@friend   %>");
$('.user-class-<%= @friend.sender_id %>').remove();

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>V</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <% if user_signed_in? %>
    <%= render "partial/navbar"%>
      <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>
      <%= yield %>
  <% else %>
    <%= yield %>
  <% end %> 
  <body>
    
  </body>
</html>

app/views/partial/_all_friends_list.html.erb
<p class="friendship-<%= allfriends.id %>">
    <%= User.find(allfriends.sender_id).name %> <%= link_to "Remove Friend", user_friendrequest_path(current_user.id, allfriends.id), method: :delete, remote:true, class:"btn btn-danger" %>
</p>

app/views/partial/_all_friends_list_sent.html.erb
<p class="friendship-<%= allfriends.id %>">
    <%= User.find(allfriends.receiver_id).name %> <%= link_to "Remove Friend", user_friendrequest_path(current_user.id, allfriends.id), method: :delete, remote:true, class:"btn btn-danger" %>
</p>

app/views/partial/_deleting_user_comment.html.erb
<div class="user-<%= user_comment.id %>">
    <div class="user-unique-post">
        <% if User.find(user_comment.user_id).image.attached? %>
            <%= image_tag(User.find(user_comment.user_id).image, class:"user-profile-image") %>
        <% else %>
        <% end %>
        <div class="user-info"> 
            <p class="user-post-username"><%= link_to User.find(user_comment.user_id).name, user_profile_page_path(user_comment.user_id), class:"link-to-title" %></p> 
            <p class="user-post-time"><%= user_comment.created_at.strftime("%d/%b/%y") %> </p> 
            <div class="post-content"><div class="post-<%= user_comment.post_id %>"><%= user_comment.body %></div></div>
            <% if user_comment.user_id == current_user.id %>
                <%= link_to "Delete", user_post_comment_path(current_user.id, user_comment.post_id, user_comment.id), method: :delete, remote: true, class:"delete-button btn btn-outline-light" %>  
                <%= link_to "Edit", edit_user_post_comment_path(current_user.id, user_comment.post_id, user_comment.id), class:"btn1 btn btn-outline-light", data:{ bs_toggle: "modal", bs_target: "#newcommentmodal", remote: true } %> 
            <% end %> 
            
        </div>
    </div>

    <div class="modal fade" id="newcommentmodal" tabindex="-1" aria-labelledby="newcommentmodalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="newusermodalLabel", style="text-align: center;"><div style="padding-left:160px;">Edit Comment</div> </h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="newcommentmodal">
            
                </div>
            
        </div>
    </div>
</div>  

app/views/partial/_edit_comment.html.erb
<%= form_with(model:[@user, post, comment], remote:true) do |f| %>
    <div class="modal-body">
        <br>
        <%= f.text_field :body, placeholder: "Comment", class: "clear-on-focus", style:" background-color: black;border: 2px solid grey; width:300px; height: 50px; color:white" %> <br>
    </div>

    <div class="modal-footer"></div> 
        <button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">Close</button>
        
        <%= f.submit class:"btn btn-outline-success"  %>
    </div>
<% end %>
<style>
    ::placeholder {
      color: white;
    }
</style>

app/views/partial/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <% if user_signed_in? %>
        <%=link_to "Facetime", user_posts_path(current_user), class:"navbar-brand" %>
      <% else %>
        <%=link_to "Facetime", new_user_session_path, class:"navbar-brand" %>
      <% end %>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Home", user_posts_path(current_user), class:"nav-link active" %>
          </li>
        <% end %>
        <% if current_user && user_signed_in? %>
          <div class="toast-class">

            <div class="toast align-items-center text-white bg-primary border-0" role="alert" aria-live="assertive" aria-atomic="true">
                <div class="toast-class d-flex">
                    <div class="toast-body">
                      <li class="nav-item">Hello, <%= current_user.name%>! &nbsp;&nbsp; Welcome to Facetime </li> 
                    </div>
                    
                </div>
            </div>
          </div>
        <% end %>
  
          
  
        </ul>
      </div>
    </div>
    <% if user_signed_in? %>
      <div class="btn-group dropstart" id="navbarNavDarkDropdown">
        <ul class="navbar-nav">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Requests
            </a>
            <ul class="dropdown-menu dropdown-menu-lg-end" aria-labelledby="navbarDarkDropdownMenuLink">
              <% if @allrequests.present? %>
                <% for allrequests in @allrequests %>
                  <li class="friendrequest-<%= allrequests.id %>"> <h6 class="dropdown-header"> You have a request from <%= User.find(allrequests.sender_id).name %> </h6> </li>  
                  <li class="friendrequest-<%= allrequests.id %>"><%= link_to "Accept", user_friendrequest_path(current_user, allrequests.id, friendrequest_id: allrequests.id ), method: :patch, remote:true, class: "dropdown-item" %> <%= link_to "Reject", user_friendrequest_path(current_user, allrequests.id, friendrequest_id: allrequests.id ), method: :delete, remote:true, class: "dropdown-item" %></li>
                <% end %>
              <% else %>
                  <li> <h6 class="dropdown-header"> You have no Request </h6> </li>
              <% end %>
            </ul>
          </li>
        </ul>
      </div>
    <% end %>

    <% if user_signed_in? %>
    <div class="collapse navbar-collapse" id="navbarNavDarkDropdown">
      <ul class="navbar-nav">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <% if current_user.image.attached? %>
              <%= image_tag( current_user.image , class: "user-profile-image") %>
            <% else %>
              Options
            <% end %>
          </a>
          <ul class="dropdown-menu dropdown-menu-lg-end" aria-labelledby="navbarDarkDropdownMenuLink">
              <li><%= link_to "Your Profile", user_profile_page_path(current_user.id), class:"dropdown-item" %> </li>
              <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete, class:"dropdown-item" %></li>
              <li><%= link_to "New Post", new_user_post_path(current_user), class:"dropdown-item", data:{ bs_toggle: "modal", bs_target: "#newpostmodal", remote: true }  %></li>
              
           
          </ul>
        </li>
      </ul>
    </div>
    <div class="modal fade" id="newpostmodal" tabindex="-1" aria-labelledby="newpostmodalLabel" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="newpostmodalLabel">New Post </h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="newpostmodal">
          
          </div>
          
      </div>
    </div>
    <% end %>
  </nav>

app/views/partial/_new_post_render.html.erb
<div class="user-post-<%= post.id %>">
            
    <div class="user-unique-post">
        
        <% if User.find(post.user_id).image.attached? %>
            <%= image_tag(User.find(post.user_id).image, class:"user-profile-image") %>
          
        <% else %>
          
        <% end %>

        
        
        <div class="user-info"> 
                
                <p class="user-post-username"><%= link_to User.find(post.user_id).name, user_profile_page_path(post.user_id), class:"link-to-title" %></p> 
                <p class="user-post-time"><%= post.created_at.strftime("%d/%b/%y") %> </p> 
                <div class="post-content"><div class="post-<%= post.id %>"><%= link_to post.body , user_post_path(current_user.id, post.id), style:"text-decoration:none; color:inherit;" %></div></div>
                <% if post.user_id == current_user.id %>
                    <div class="edit-line-comment"></div>
                    <%= link_to "Delete", user_post_path(current_user.id, post.id), method: :delete, remote: true, class:"delete-button btn btn-outline-light" %>  
                    <%= link_to "Edit", edit_user_post_path(current_user.id, post.id), class:"btn1 btn btn-outline-light", data:{ bs_toggle: "modal", bs_target: "#newusermodal", remote: true } %>

                <% end %>
        </div>
        
        
    </div>
</div>

app/views/posts/destroy.js.erb
$( ".user-post-<%= @post.id %>").remove();

app/views/posts/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body class="html-class-index">
    <div class="left-rectangle-box"> 
        <h3 style="text-align: center; margin-top: 15px;"> All Friends </h3>
        <div class="all-users-div">

            <div id="allfriendslist">
                <% for allfriends in @allfriends_friendrequest_sent %>
                    <%= render 'partial/all_friends_list_sent', allfriends:allfriends %>
                <% end %>
                <% for allfriends in @allfriends_friendrequest_received %>
                    <%= render 'partial/all_friends_list', allfriends:allfriends %>
                <% end %>    
            </div>
        </div>

    </div>
    <div class="rectangle-box">
        <div class="allusers" >
            <h4 style="text-align: center; margin-top: 15px;"> All USers </h4>
            <div class="all-users-div">
                <% for user in @allusers %>
                    <% if user.id== current_user.id %>
                        <% next %>
                    <% else %>
                        <% if Friendrequest.find_by(sender_id:user.id, status:"pending", receiver_id:current_user.id).present? %>
                            <p class="user-class-<%= user.id %>">
                                <%= link_to user.name, user_profile_page_path(user.id), class:"link-to-title" %> sends you Friendrequest
                            </p>
                        <% else %>
                            <% if Friendrequest.find_by(sender_id:current_user.id, status:"pending", receiver_id:user.id).present?  %>
                                <p class="user-class-<%= user.id %>">
                                    Friend Request send! <%= link_to "Undo", user_friendrequest_path(current_user, Friendrequest.find_by(sender_id:current_user.id, status:"pending", receiver_id:user.id) ), method: :delete, remote:true ,class:"btn btn-info" %>
                                </p>
                            <% else %>
                                <% if Friendrequest.find_by(sender_id:current_user.id, status:"approved", receiver_id:user.id).present? || Friendrequest.find_by(sender_id:user.id, status:"approved", receiver_id:current_user.id).present? %>
                                    <% next %>
                                <% else %>
                                    <p class="user-class-<%= user.id %>">
                                        <%= link_to user.name, user_profile_page_path(user.id), class:"link-to-title" %> <%= link_to "send friend request", user_friendrequests_path( current_user.id, receiver_id: user.id), method: :post, remote:true, class:"btn btn-primary" %>
                                    </p>
                                <% end %>
                            <% end %>
                        <% end %>
                    <% end %>
                                
                <% end %>
            </div>
                                
        </div>


    </div>
    
    <div class="saman">
        <% for post in @all_posts %>
            <div class="user-post-<%= post.id %>">
                <div class="user-unique-post">
                    <% if User.find(post.user_id).image.attached? %>
                        <%= image_tag(User.find(post.user_id).image, class:"user-profile-image") %>
                    <% else %>
                    <% end %>
                    <div class="user-info"> 
                    
                        <p class="user-post-username"><%= link_to User.find(post.user_id).name, user_profile_page_path(post.user_id), class:"link-to-title",  data:{ bs_toggle: "modal", bs_target: "#profile-modal", remote: true }%></p> 
                        <p class="user-post-time"><%= post.created_at.strftime("%d/%b/%y") %> </p> 
                        <div class="post-content">
                            <div class="post-<%= post.id %>">
                                <%= link_to post.body , user_post_path(current_user.id, post.id), style:"text-decoration:none; color:inherit;" %>
                            </div>
                        </div>
                        <% if post.user_id == current_user.id %>
                            <div class="edit-line-comment"></div>
                                <%= link_to "Delete", user_post_path(current_user.id, post.id), method: :delete, remote: true, class:"delete-button btn btn-outline-light" %>  
                                <%= link_to "Edit", edit_user_post_path(current_user.id, post.id), class:"btn1 btn btn-outline-light", data:{ bs_toggle: "modal", bs_target: "#newusermodal", remote: true } %>

                        <% end %>
                    </div>
            
            
                </div>
            </div>
        
        <% end %>
    </div>
    <br>
    <!-- Button trigger modal -->
  
  <!-- Button trigger modal -->

  
  <!-- Modal -->
  
  <div class="modal fade" id="newusermodal" tabindex="-1" aria-labelledby="newusermodalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="newusermodalLabel"><div style="padding-left:160px;">Edit Post</div> </h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="newusermodal">
        
        </div>
        
    </div>
  </div>
</div>  
  
   
    
   
    <br>
    <br>
    <div class="modal fade" id="profile-modal" tabindex="-1" aria-labelledby="profile-modalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="profile-modalLabel"><div style="padding-left:160px;">Edit Post 11</div> </h5>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="profile-modal">
            
            </div>
            
          </div>
      </div>
    </div>
    <br><br>

    <script>
        document.addEventListener('DOMContentLoaded', function() {
        var toastEl = document.querySelector('.toast')
        var toast = new bootstrap.Toast(toastEl)
        <% if current_user && user_signed_in? %>
            toast.show()
        <% end %>
      
        })
    </script>
</body>
</html>

















  

app/views/posts/show.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body class="html-class-index">

    <div class="user-unique-post">
        <% if User.find(@post.user_id).image.attached? %>
            <%= image_tag(User.find(@post.user_id).image, class:"user-profile-image") %>
        <% else %>
        <% end %>
        <div class="user-info"> 
            <p class="user-post-username"><%= link_to User.find(@post.user_id).name, user_profile_page_path(@post.user_id), class:"link-to-title" %></p> 
            <p class="user-post-time"><%= @post.created_at.strftime("%d/%b/%y") %> </p> 
            <div class="post-content">
                <%= link_to @post.body , user_post_path(current_user.id, @post.id), style:"text-decoration:none; color:inherit;" %>
            </div> 
        </div>
    </div>
    <div id="comments_id" >
        <% @all_comments.each do |allcomment|    %>
            <%= render 'partial/deleting_user_comment', user_comment:allcomment %>
        <% end %>
    </div>

    <div class="user-unique-post">
        <%= form_with(model:[current_user, @post, @comment], local: false) do |f| %>
            <div class="form-class">
                <%= f.text_area :body,  placeholder: "Add a comment", class: "clear-on-focus", style:" background-color: black;border: 2px solid grey; width:300px; height: 50px; color:white" %>
                <%= f.submit class:"form-submit-button" %>
            </div>
        <%  end %>
    </div>  
    <style>
        ::placeholder {
            color: white;
        }
    </style>
</body>
</html>

app/views/users/profile_page.html.erb
<h1 style="text-align: center; padding-top:100px; font-size:5px;">   </h1>
<div class="user-container">
       
    <div class="p1">Name </div> <div class="p2"> <%= @user_details.name %> </div> <br>
    
    <div class="p1">Email</div> <div class="p2"> <%= @user_details.email %></div>
    
</div>

<div><%= link_to User.find(current_user.id).name, user_profile_page_path(current_user.id), class:"link-to-title", data:{ bs_toggle: "modal", bs_target: "#newuserprofilemodal", remote: true } %></div> 


<div class="modal fade" id="newuserprofilemodal" tabindex="-1" aria-labelledby="newuserprofilemodalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="newuserprofilemodalLabel">
                    <div style="padding-left:160px;">
                        Edit Post
                    </div> 
                </h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="newuserprofilemodal">
    
            </div>
        </div>

    </div>
</div> 